# Generated by Django 5.0.6 on 2024-06-05 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_initials', models.CharField(max_length=3)),
                ('property_title', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=200)),
                ('property_price', models.CharField(max_length=200)),
                ('bedrooms_no', models.CharField(max_length=200)),
                ('bathrooms_no', models.CharField(max_length=200)),
                ('property_location', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=200)),
                ('property_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('user_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.userlisting')),
            ],
        ),
    ]
